MonoTest/Models/ErrorViewModel.cs
namespace MonoTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MonoTest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MonoTest.Models;
using System.Diagnostics;

namespace MonoTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MonoTest/Controllers/ModelController.cs
using cloudscribe.Pagination.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VehicleServices.Data;
using VehicleServices.Interfaces;
using VehicleServices.Models;

namespace MonoTest.Controllers
{
    public class ModelController : Controller
    {
        private readonly IVehicleModel _service;

        public ModelController(IVehicleModel service)
        {
            _service = service;
        }

        public IActionResult Index(string searchString, string sortOrder, int pageNumber = 1, int pageSize = 3)
        {
            var result = _service.GetAllModel(this, searchString, sortOrder, pageNumber, pageSize);

            return View(result);
        }

        //CREATE
        //GET
        public IActionResult Create()
        {
            return View(_service.AddModelGet());
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Vehicles obj)
        {

            if (_service.AddModel(ModelState, obj))
            {
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //EDIT
        //GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            if (_service.UpdateDeleteModelGet(id) == null)
            {
                return NotFound();
            }

            return View(await _service.UpdateDeleteModelGet(id));
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(VehicleModel obj)
        {

            if (_service.UpdatePostModel(ModelState, obj))
            {
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //DELETE
        //GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            if (_service.UpdateDeleteModelGet(id) == null)
            {
                return NotFound();
            }

            return View(await _service.UpdateDeleteModelGet(id));
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int? id)
        {
            Task<bool> deleteTask = _service.DeletePostModel(id);

            bool b = await deleteTask;

            if (b)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

    }
}

MonoTest/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using VehicleServices.Data;
using VehicleServices.Interfaces;
using VehicleServices.Models;

namespace MonoTest.Controllers
{
    public class VehicleController : Controller
    {
        private readonly IVehicleMake _service;

        public VehicleController(IVehicleMake service)
        {
            _service = service;
        }

        public IActionResult Index(string searchString, string sortOrder, int pageNumber = 1, int pageSize = 3)
        {
            var result = _service.GetAllMake(this, searchString, sortOrder, pageNumber, pageSize);

            return View(result);
        }

        //CREATE
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(VehicleMake obj)
        {

            if (_service.AddMake(ModelState, obj))
            {
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //EDIT
        //GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            if (_service.UpdateDeleteMakeGet(id) == null)
            {
                return NotFound();
            }

            return View(await _service.UpdateDeleteMakeGet(id));
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(VehicleMake obj)
        {

            if (_service.UpdatePostMake(ModelState, obj))
            {
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //DELETE
        //GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            if (_service.UpdateDeleteMakeGet(id) == null)
            {
                return NotFound();
            }

            return View(await _service.UpdateDeleteMakeGet(id));
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int? id)
        {
            Task<bool> deleteTask = _service.DeletePostMake(id);

            bool b = await deleteTask;

            if (b)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

MonoTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MonoTest/Views/Model/Create.cshtml
@model VehicleServices.Models.Vehicles

<form method="post" style="width: 60%">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create vehicle</h2>
			<hr />
		</div>
		<div class="mb-3">
			<select asp-for="vehicleModel.make_id" asp-items="Model.vehicleMakeList" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
				<option selected>Select vehicle make</option>
			</select>
			
		</div>
		<div class="mb-3">
			<label asp-for="vehicleModel.name"></label>
			<input asp-for="vehicleModel.name" class="form-control" />
			<span asp-validation-for="vehicleModel.name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="vehicleModel.abrv"></label>
			<input asp-for="vehicleModel.abrv" class="form-control" />
			<span asp-validation-for="vehicleModel.abrv" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="Model" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back
		</a>
	</div>
</form>

MonoTest/Views/Model/Delete.cshtml
@model VehicleServices.Models.VehicleModel

<form method="post" asp-action="Delete" style="width: 60%">
	<input asp-for="id" hidden />
	<input asp-for="make_id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete vehicle</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="name"></label>
			<input asp-for="name" class="form-control" disabled/>
		</div>
		<div class="mb-3">
			<label asp-for="abrv"></label>
			<input asp-for="abrv" class="form-control" disabled/>
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Model" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back
		</a>
	</div>
</form>

MonoTest/Views/Model/Edit.cshtml
@model VehicleServices.Models.VehicleModel

<form method="post" asp-action="Edit" style="width: 60%">
	<input asp-for="make_id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit vehicle</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="name"></label>
			<input asp-for="name" class="form-control"/>
			<span asp-validation-for="name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="abrv"></label>
			<input asp-for="abrv" class="form-control"/>
			<span asp-validation-for="abrv" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Model" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back
		</a>
	</div>
</form>

MonoTest/Views/Model/Index.cshtml
@model cloudscribe.Pagination.Models.PagedResult<VehicleServices.Models.VehicleModel>
@{
    ViewData["Title"] = "Index";
    ViewData["Controller"] = "Model";
    ViewData["Action"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Model List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Model" asp-action="Create" class="btn btn-primary">
                Create new model
            </a>
        </div>
    </div>

    <br />

    <form asp-action="Index" method="get">
        <div>
            <p>
                Find Make: <input type="text" name="searchString" value="@ViewBag.CurrentFilter" />
                <input type="submit" value="Search" class="btn btn-info" />
                <a asp-action="Index">Remove filter</a>
            </p>
        </div>
    </form>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.NameSortParam"
                       asp-route-pageNumber="@Model.PageNumber">
                        Name
                    </a>
                </th>
                <th>
                    Abrv
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.Data)
            {
                <tr>
                    <td width="50%">
                        @obj.name
                    </td>
                    <td width="30%">
                        @obj.abrv
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Model" asp-action="Edit" asp-route-id="@obj.id"
                               class="btn btn-primary mx-2">Edit</a>
                            <a asp-controller="Model" asp-action="Delete" asp-route-id="@obj.id"
                               class="btn btn-danger mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <partial name="PaginationPartial" view-data="ViewData" model="Model" />
</div>

MonoTest/Views/Shared/PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber="Model.PageNumber"
           cs-paging-totalitems="Model.TotalItems"
           cs-paging-pagesize="Model.PageSize"
           cs-pagenumber-param="pagenumber"
           asp-route-searchString="@ViewBag.CurrentFilter"
           asp-route-sortOrder="@ViewBag.CurrentSortOrder"
           asp-controller=@ViewData["Controller"]
           asp-action=@ViewData["Action"]
           cs-pager-li-current-class="page-item active"
           cs-pager-li-other-class="page-item"
           cs-pager-li-non-active-class="page-item disabled"
           cs-pager-link-current-class="page-link"
           cs-pager-link-other-class="page-link">
</cs-pager>

MonoTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonoTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MonoTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MonoTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="Index">VehicleMake</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Model" asp-action="Index">VehicleModel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MonoTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MonoTest/Views/Vehicle/Create.cshtml
@model VehicleServices.Models.VehicleMake

<form method="post" style="width: 60%">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create vehicle</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="name"></label>
			<input asp-for="name" class="form-control"/>
			<span asp-validation-for="name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="abrv"></label>
			<input asp-for="abrv" class="form-control"/>
			<span asp-validation-for="abrv" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="Vehicle" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back
		</a>
	</div>
</form>

MonoTest/Views/Vehicle/Delete.cshtml
@model VehicleServices.Models.VehicleMake

<form method="post" asp-action="Delete" style="width: 60%">
	<input asp-for="id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete vehicle</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="name"></label>
			<input asp-for="name" class="form-control" disabled/>
		</div>
		<div class="mb-3">
			<label asp-for="abrv"></label>
			<input asp-for="abrv" class="form-control" disabled/>
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Vehicle" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back
		</a>
	</div>
</form>

MonoTest/Views/Vehicle/Edit.cshtml
@model VehicleServices.Models.VehicleMake

<form method="post" asp-action="Edit" style="width: 60%">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit vehicle</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="name"></label>
			<input asp-for="name" class="form-control"/>
			<span asp-validation-for="name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="abrv"></label>
			<input asp-for="abrv" class="form-control"/>
			<span asp-validation-for="abrv" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Vehicle" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back
		</a>
	</div>
</form>

MonoTest/Views/Vehicle/Index.cshtml
@model cloudscribe.Pagination.Models.PagedResult<VehicleServices.Models.VehicleMake>
@{
    ViewData["Title"] = "Index";
    ViewData["Controller"] = "Vehicle";
    ViewData["Action"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Vehicle List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Vehicle" asp-action="Create" class="btn btn-primary">
                Create new vehicle
            </a>
        </div>
    </div>

    <br />

    <form asp-action="Index" method="get">
        <div>
            <p>
                Find Make: <input type="text" name="searchString" value="@ViewBag.CurrentFilter" />
                <input type="submit" value="Search" class="btn btn-info" />
                <a asp-action="Index">Remove filter</a>
            </p>
        </div>
    </form>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index" 
                        asp-route-sortOrder="@ViewBag.NameSortParam"
                        asp-route-pageNumber="@Model.PageNumber">
                        Name
                    </a>
                </th>
                <th>
                    Abrv
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var obj in Model.Data)
            {
                <tr>
                    <td width="50%">
                        @obj.name
                    </td>
                    <td width="30%">
                        @obj.abrv
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Vehicle" asp-action="Edit" asp-route-id="@obj.id"
                            class="btn btn-primary mx-2">Edit</a>
                            <a asp-controller="Vehicle" asp-action="Delete" asp-route-id="@obj.id"
                               class="btn btn-danger mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <partial name="PaginationPartial" view-data="ViewData" model="Model" />
</div>